#!/usr/bin/env bash

# Script to make data cards for Higgs Combine
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter
# You need to have a symbolic link called "trees" pointing to your trees

lumi=3000.

mca=susy-upgrade/mca_2LSOS.txt
systs=susy-upgrade/systs.txt
trees=trees/
#dirBins=susy-upgrade/bins/binning_5met_4mll_3slep/
dirBins=susy-upgrade/bins/binning_5met_4mll_3slep_realMET/
dirCards=susy-upgrade/cards/

# If cards directory exists, exit
if [ -d "${dirCards}" ]; then
    echo "Cards directory ${dirCards} exists already."
    echo "Exit."
    exit
fi

mkdir -p "${dirCards}"

signals=()
#signals+=(N2C1_100_60_Delphes_14TeV)
#signals+=(N2C1_100_65_Delphes_14TeV)
#signals+=(N2C1_100_70_Delphes_14TeV)
#signals+=(N2C1_100_75_Delphes_14TeV)
#signals+=(N2C1_100_80_Delphes_14TeV)
#signals+=(N2C1_100_85_Delphes_14TeV)
#signals+=(N2C1_100_90_Delphes_14TeV)
#signals+=(N2C1_100_93_Delphes_14TeV)
#signals+=(N2C1_100_95_Delphes_14TeV)
#signals+=(N2C1_150_110_Delphes_14TeV)
#signals+=(N2C1_150_115_Delphes_14TeV)
#signals+=(N2C1_150_120_Delphes_14TeV)
#signals+=(N2C1_150_125_Delphes_14TeV)
#signals+=(N2C1_150_130_Delphes_14TeV)
#signals+=(N2C1_150_135_Delphes_14TeV)
#signals+=(N2C1_150_140_Delphes_14TeV)
#signals+=(N2C1_150_143_Delphes_14TeV)
#signals+=(N2C1_150_145_Delphes_14TeV)
#signals+=(N2C1_200_160_Delphes_14TeV)
#signals+=(N2C1_200_165_Delphes_14TeV)
#signals+=(N2C1_200_170_Delphes_14TeV)
#signals+=(N2C1_200_175_Delphes_14TeV)
#signals+=(N2C1_200_180_Delphes_14TeV)
#signals+=(N2C1_200_185_Delphes_14TeV)
#signals+=(N2C1_200_190_Delphes_14TeV)
#signals+=(N2C1_200_193_Delphes_14TeV)
#signals+=(N2C1_200_195_Delphes_14TeV)
#signals+=(N2C1_250_210_Delphes_14TeV)
#signals+=(N2C1_250_215_Delphes_14TeV)
#signals+=(N2C1_250_220_Delphes_14TeV)
#signals+=(N2C1_250_225_Delphes_14TeV)
#signals+=(N2C1_250_230_Delphes_14TeV)
#signals+=(N2C1_250_235_Delphes_14TeV)
#signals+=(N2C1_250_240_Delphes_14TeV)
#signals+=(N2C1_250_243_Delphes_14TeV)
#signals+=(N2C1_250_245_Delphes_14TeV)
#signals+=(N2C1_300_260_Delphes_14TeV)
#signals+=(N2C1_300_265_Delphes_14TeV)
#signals+=(N2C1_300_270_Delphes_14TeV)
#signals+=(N2C1_300_275_Delphes_14TeV)
#signals+=(N2C1_300_280_Delphes_14TeV)
#signals+=(N2C1_300_285_Delphes_14TeV)
#signals+=(N2C1_300_290_Delphes_14TeV)
#signals+=(N2C1_300_293_Delphes_14TeV)
#signals+=(N2C1_300_295_Delphes_14TeV)
#signals+=(N2C1_350_310_Delphes_14TeV)
#signals+=(N2C1_350_315_Delphes_14TeV)
#signals+=(N2C1_350_320_Delphes_14TeV)
#signals+=(N2C1_350_325_Delphes_14TeV)
#signals+=(N2C1_350_330_Delphes_14TeV)
#signals+=(N2C1_350_335_Delphes_14TeV)
#signals+=(N2C1_350_340_Delphes_14TeV)
#signals+=(N2C1_350_343_Delphes_14TeV)
#signals+=(N2C1_350_345_Delphes_14TeV)
#signals+=(N2C1_400_360_Delphes_14TeV)
#signals+=(N2C1_400_365_Delphes_14TeV)
#signals+=(N2C1_400_370_Delphes_14TeV)
#signals+=(N2C1_400_375_Delphes_14TeV)
#signals+=(N2C1_400_380_Delphes_14TeV)
#signals+=(N2C1_400_385_Delphes_14TeV)
#signals+=(N2C1_400_390_Delphes_14TeV)
#signals+=(N2C1_400_393_Delphes_14TeV)
#signals+=(N2C1_400_395_Delphes_14TeV)
#signals+=(N2C1_450_410_Delphes_14TeV)
#signals+=(N2C1_450_415_Delphes_14TeV)
#signals+=(N2C1_450_420_Delphes_14TeV)
#signals+=(N2C1_450_425_Delphes_14TeV)
#signals+=(N2C1_450_430_Delphes_14TeV)
#signals+=(N2C1_450_435_Delphes_14TeV)
#signals+=(N2C1_450_440_Delphes_14TeV)
#signals+=(N2C1_450_443_Delphes_14TeV)
#signals+=(N2C1_450_445_Delphes_14TeV)
#signals+=(N2C1_500_460_Delphes_14TeV)
#signals+=(N2C1_500_465_Delphes_14TeV)
#signals+=(N2C1_500_470_Delphes_14TeV)
#signals+=(N2C1_500_475_Delphes_14TeV)
#signals+=(N2C1_500_480_Delphes_14TeV)
#signals+=(N2C1_500_485_Delphes_14TeV)
#signals+=(N2C1_500_490_Delphes_14TeV)
#signals+=(N2C1_500_493_Delphes_14TeV)
#signals+=(N2C1_500_495_Delphes_14TeV)
#signals+=(N2C1_550_510_Delphes_14TeV)
#signals+=(N2C1_550_515_Delphes_14TeV)
#signals+=(N2C1_550_520_Delphes_14TeV)
#signals+=(N2C1_550_525_Delphes_14TeV)
#signals+=(N2C1_550_530_Delphes_14TeV)
#signals+=(N2C1_550_535_Delphes_14TeV)
#signals+=(N2C1_550_540_Delphes_14TeV)
#signals+=(N2C1_550_543_Delphes_14TeV)
#signals+=(N2C1_550_545_Delphes_14TeV)
#signals+=(N2C1_600_560_Delphes_14TeV)
#signals+=(N2C1_600_565_Delphes_14TeV)
#signals+=(N2C1_600_570_Delphes_14TeV)
#signals+=(N2C1_600_575_Delphes_14TeV)
#signals+=(N2C1_600_580_Delphes_14TeV)
#signals+=(N2C1_600_585_Delphes_14TeV)
#signals+=(N2C1_600_590_Delphes_14TeV)
#signals+=(N2C1_600_593_Delphes_14TeV)
#signals+=(N2C1_600_595_Delphes_14TeV)
#signals+=(N2C1_650_610_Delphes_14TeV)
#signals+=(N2C1_650_615_Delphes_14TeV)
#signals+=(N2C1_650_620_Delphes_14TeV)
#signals+=(N2C1_650_625_Delphes_14TeV)
#signals+=(N2C1_650_630_Delphes_14TeV)
#signals+=(N2C1_650_635_Delphes_14TeV)
#signals+=(N2C1_650_640_Delphes_14TeV)
#signals+=(N2C1_650_643_Delphes_14TeV)
#signals+=(N2C1_650_645_Delphes_14TeV)
#signals+=(MSSM-higgsino_13TeV_100_300)
#signals+=(MSSM-higgsino_13TeV_100_400)
#signals+=(MSSM-higgsino_13TeV_100_500)
#signals+=(MSSM-higgsino_13TeV_100_600)
#signals+=(MSSM-higgsino_13TeV_100_800)
#signals+=(MSSM-higgsino_13TeV_100_1000)
#signals+=(MSSM-higgsino_13TeV_100_1200)
#signals+=(MSSM-higgsino_13TeV_120_300)
#signals+=(MSSM-higgsino_13TeV_120_400)
#signals+=(MSSM-higgsino_13TeV_120_500)
#signals+=(MSSM-higgsino_13TeV_120_600)
#signals+=(MSSM-higgsino_13TeV_120_800)
#signals+=(MSSM-higgsino_13TeV_120_1000)
#signals+=(MSSM-higgsino_13TeV_120_1200)
#signals+=(MSSM-higgsino_13TeV_140_300)
#signals+=(MSSM-higgsino_13TeV_140_400)
#signals+=(MSSM-higgsino_13TeV_140_500)
#signals+=(MSSM-higgsino_13TeV_140_600)
#signals+=(MSSM-higgsino_13TeV_140_800)
#signals+=(MSSM-higgsino_13TeV_140_1000)
#signals+=(MSSM-higgsino_13TeV_140_1200)
#signals+=(MSSM-higgsino_13TeV_160_300)
#signals+=(MSSM-higgsino_13TeV_160_400)
#signals+=(MSSM-higgsino_13TeV_160_500)
#signals+=(MSSM-higgsino_13TeV_160_600)
#signals+=(MSSM-higgsino_13TeV_160_800)
#signals+=(MSSM-higgsino_13TeV_160_1000)
#signals+=(MSSM-higgsino_13TeV_160_1200)
#signals+=(MSSM-higgsino_13TeV_180_300)
#signals+=(MSSM-higgsino_13TeV_180_400)
#signals+=(MSSM-higgsino_13TeV_180_500)
#signals+=(MSSM-higgsino_13TeV_180_600)
#signals+=(MSSM-higgsino_13TeV_180_800)
#signals+=(MSSM-higgsino_13TeV_180_1000)
#signals+=(MSSM-higgsino_13TeV_180_1200)
#signals+=(MSSM-higgsino_13TeV_200_300)
#signals+=(MSSM-higgsino_13TeV_200_400)
#signals+=(MSSM-higgsino_13TeV_200_500)
#signals+=(MSSM-higgsino_13TeV_200_600)
#signals+=(MSSM-higgsino_13TeV_200_800)
#signals+=(MSSM-higgsino_13TeV_200_1000)
#signals+=(MSSM-higgsino_13TeV_200_1200)
#signals+=(MSSM-higgsino_13TeV_220_300)
#signals+=(MSSM-higgsino_13TeV_220_400)
#signals+=(MSSM-higgsino_13TeV_220_500)
#signals+=(MSSM-higgsino_13TeV_220_600)
#signals+=(MSSM-higgsino_13TeV_220_800)
#signals+=(MSSM-higgsino_13TeV_220_1000)
#signals+=(MSSM-higgsino_13TeV_220_1200)
#signals+=(MSSM-higgsino_13TeV_240_300)
#signals+=(MSSM-higgsino_13TeV_240_400)
#signals+=(MSSM-higgsino_13TeV_240_500)
#signals+=(MSSM-higgsino_13TeV_240_600)
#signals+=(MSSM-higgsino_13TeV_240_800)
#signals+=(MSSM-higgsino_13TeV_240_1000)
#signals+=(MSSM-higgsino_13TeV_240_1200)
signals+=(TChipmWW_Delphes_13TeV_100_60)
signals+=(TChipmWW_Delphes_13TeV_100_70)
signals+=(TChipmWW_Delphes_13TeV_100_80)
signals+=(TChipmWW_Delphes_13TeV_100_90)
signals+=(TChipmWW_Delphes_13TeV_125_85)
signals+=(TChipmWW_Delphes_13TeV_125_95)
signals+=(TChipmWW_Delphes_13TeV_125_105)
signals+=(TChipmWW_Delphes_13TeV_125_115)
signals+=(TChipmWW_Delphes_13TeV_150_110)
signals+=(TChipmWW_Delphes_13TeV_150_120)
signals+=(TChipmWW_Delphes_13TeV_150_130)
signals+=(TChipmWW_Delphes_13TeV_150_140)
signals+=(TChipmWW_Delphes_13TeV_175_135)
signals+=(TChipmWW_Delphes_13TeV_175_145)
signals+=(TChipmWW_Delphes_13TeV_175_155)
signals+=(TChipmWW_Delphes_13TeV_175_165)
signals+=(TChipmWW_Delphes_13TeV_200_160)
signals+=(TChipmWW_Delphes_13TeV_200_170)
signals+=(TChipmWW_Delphes_13TeV_200_180)
signals+=(TChipmWW_Delphes_13TeV_200_190)
signals+=(TChipmWW_Delphes_13TeV_225_185)
signals+=(TChipmWW_Delphes_13TeV_225_195)
signals+=(TChipmWW_Delphes_13TeV_225_205)
signals+=(TChipmWW_Delphes_13TeV_225_215)
signals+=(TChipmWW_Delphes_13TeV_250_210)
signals+=(TChipmWW_Delphes_13TeV_250_220)
signals+=(TChipmWW_Delphes_13TeV_250_230)
signals+=(TChipmWW_Delphes_13TeV_250_240)
signals+=(TChipmWW_Delphes_13TeV_275_235)
signals+=(TChipmWW_Delphes_13TeV_275_245)
signals+=(TChipmWW_Delphes_13TeV_275_255)
signals+=(TChipmWW_Delphes_13TeV_275_265)
signals+=(TChipmWW_Delphes_13TeV_300_260)
signals+=(TChipmWW_Delphes_13TeV_300_270)
signals+=(TChipmWW_Delphes_13TeV_300_280)
signals+=(TChipmWW_Delphes_13TeV_300_290)

# Make sure that all signal is enabled in mca
sed -i "s/SkipMe *= *True/SkipMe=False/g" "${mca}"

for signal in "${signals[@]}"; do
    echo "Make datacards for signal point ${signal}... " 1>&2
    for cuts in "${dirBins}"/*; do
        #region="${cuts##*/}"
        #region="${region%.*}"
        #echo -n "${region}... "
        #echo makeCountingCards.py \
        #    "${mca}" \
        #    "${cuts}" \
        #    "${systs}" \
        #    -P "${trees}" \
        #    -l "${lumi}" \
        #    -j 1 \
        #    --s2v \
        #    --tree treeProducerSusyUpgrade \
        #    --obj Delphes \
        #    --AP \
        #    -p Wj2,DY2,tt,WW,"${signal}" \
        #    \> "${dirCards}"/"${signal}"_"${cuts##*/}"
        echo "${mca}" "${cuts}" "${systs}" "${trees}" "${lumi}" "${signal}" \
            "${dirCards}" "${cuts##*/}"
    done
done | xargs -L 1 -P $(( $(nproc) - 2 )) bash -c 'python makeCountingCards.py \
    "${0}" \
    "${1}" \
    "${2}" \
    -P "${3}" \
    -l "${4}" \
    -j 1 \
    --s2v \
    --tree treeProducerSusyUpgrade \
    --obj Delphes \
    --AP \
    -p Wj2,DY2,tt,WW,"${5}" > "${6}"/"${5}"_"${7}"'
echo "Bye."
