#!/usr/bin/env bash

# Script to make plots
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter
# You need to have a symbolic link called "trees" pointing to your trees

lumi=3000.

mca=susy-upgrade/mca_2LSOS.txt
cuts=susy-upgrade/cuts_2LSOS.txt
trees=trees/
plots=susy-upgrade/plots_2LSOS.txt

# QCD estimation, define QCD as signal
python mcPlots.py \
    "${mca}" \
    "${cuts}" \
    "${plots}" \
    -P "${trees}" \
    -l "${lumi}" \
    -j $(nproc) \
    -f \
    --tree treeProducerSusyUpgrade \
    --obj Delphes \
    --showSignificance \
    --maxRatioRange 0.05 1.95 \
    --fixRatioRange \
    --noErrorBandOnRatio \
    --noStackSig \
    --showIndivSigs \
    --showMCError \
    --emptyStack \
    --printBinAuto \
    --legendFontSize 0.028 \
    --noCms \
    --lspam "#bf{CMS} #it{Sim. Prel.}" \
    --rspam "%(lumi) (14 TeV)"

# Useful options:
# -e: show statistical errors
# --showIndivSigShapes: Don't normalize signal to cross section
# --emptyStack: Allow empty histograms
# --showRatio: Show ratio plot
# --ratioDen sample1: For --showRatio, use sample 1 in denominator
# --ratioNums sample2: For --showRatio, use sample 2 in numerator
# --ratioYLabel: Label for ratio plot
# --plotmode mode: Use plotting mode, e.g. nostack
