#!/usr/bin/env bash

# Script to make plots
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter
# You need to have a symbolic link called "trees" pointing to your trees

lumi=3000.

mca=susy-upgrade/mca_2LSOS.txt
cuts=susy-upgrade/cuts_2LSOS.txt
trees=trees/
plots=susy-upgrade/plots_2LSOS.txt

# QCD estimation, define QCD as signal
python mcPlots.py \
    "${mca}" \
    "${cuts}" \
    "${plots}" \
    -P "${trees}" \
    -l "${lumi}" \
    -j $(nproc) \
    --tree treeProducerSusyUpgrade \
    --obj Delphes \
    --showRatio \
    --maxRatioRange 0.05 1.95 \
    --fixRatioRange \
    --noErrorBandOnRatio \
    --noStackSig \
    --showIndivSigs
