#!/usr/bin/env bash

# Script to make data cards for Higgs Combine
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter
# You need to have a symbolic link called "trees" pointing to your trees

lumi=3000.

mca=susy-upgrade/mca_2LSOS.txt
trees=trees/
dirBins=susy-upgrade/bins/
dirCards=susy-upgrade/cards/

mkdir -p "${dirCards}"

signals=()
signals+=(S_100_60_Delphes_v10)
signals+=(S_100_70_Delphes_v10)
signals+=(S_100_80_Delphes_v10)
signals+=(S_100_85_Delphes_v10)
signals+=(S_100_90_Delphes_v10)
signals+=(S_100_93_Delphes_v10)
signals+=(S_125_85_Delphes_v10)
signals+=(S_125_95_Delphes_v10)
signals+=(S_125_105_Delphes_v10)
signals+=(S_125_110_Delphes_v10)
signals+=(S_125_115_Delphes_v10)
signals+=(S_125_118_Delphes_v10)
signals+=(S_150_110_Delphes_v10)
signals+=(S_150_120_Delphes_v10)
signals+=(S_150_130_Delphes_v10)
signals+=(S_150_135_Delphes_v10)
signals+=(S_150_140_Delphes_v10)
signals+=(S_150_143_Delphes_v10)
signals+=(S_175_135_Delphes_v10)
signals+=(S_175_145_Delphes_v10)
signals+=(S_175_155_Delphes_v10)
signals+=(S_175_160_Delphes_v10)
signals+=(S_175_165_Delphes_v10)
signals+=(S_175_168_Delphes_v10)
signals+=(S_200_160_Delphes_v10)
signals+=(S_200_170_Delphes_v10)
signals+=(S_200_180_Delphes_v10)
signals+=(S_200_185_Delphes_v10)
signals+=(S_200_190_Delphes_v10)
signals+=(S_200_193_Delphes_v10)
signals+=(S_225_185_Delphes_v10)
signals+=(S_225_195_Delphes_v10)
signals+=(S_225_205_Delphes_v10)
signals+=(S_225_210_Delphes_v10)
signals+=(S_225_215_Delphes_v10)
signals+=(S_225_218_Delphes_v10)
signals+=(S_250_210_Delphes_v10)
signals+=(S_250_220_Delphes_v10)
signals+=(S_250_230_Delphes_v10)
signals+=(S_250_235_Delphes_v10)
signals+=(S_250_240_Delphes_v10)
signals+=(S_250_243_Delphes_v10)
signals+=(S_275_235_Delphes_v10)
signals+=(S_275_245_Delphes_v10)
signals+=(S_275_255_Delphes_v10)
signals+=(S_275_260_Delphes_v10)
signals+=(S_275_265_Delphes_v10)
signals+=(S_275_268_Delphes_v10)
signals+=(S_300_260_Delphes_v10)
signals+=(S_300_270_Delphes_v10)
signals+=(S_300_280_Delphes_v10)
signals+=(S_300_285_Delphes_v10)
signals+=(S_300_290_Delphes_v10)
signals+=(S_300_293_Delphes_v10)

for signal in "${signals[@]}"; do
    echo -n "Make datacards for signal point ${signal}... "
    for cuts in "${dirBins}"/*; do
        region="${cuts##*/}"
        region="${region%.*}"
        echo -n "${region}... "
        python makeCountingCards.py \
            <(sed "/${signal}/s/SkipMe *= *True/SkipMe=False/g" "${mca}") \
            "${cuts}" \
            -P "${trees}" \
            -l "${lumi}" \
            -j 20 \
            --s2v \
            --tree treeProducerSusyUpgrade \
            --obj Delphes \
            --AP \
            -p Wj2,DY2,tt,WW,"${signal}" \
            > "${dirCards}"/"${signal}"_"${cuts##*/}"
    done
    echo "Done."
done
