#!/usr/bin/env bash

# Script to make cutflow
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter
# You need to have a symbolic link called "trees" pointing to your trees

lumi=3000.
echo "LUMI SET TO ${lumi}!"

mca=susy-upgrade/mca_2LSOS.txt
cuts=susy-upgrade/cuts_2LSOS.txt
trees=trees/

python mcAnalysis.py \
    "${mca}" \
    "${cuts}" \
    -P "${trees}" \
    -l "${lumi}" \
    -j 22 \
    -G \
    --s2v \
    --tree treeProducerSusyUpgrade \
    --obj Delphes

# Useful options:
# -e: show statistical errors
# -u: don't use any weights
# -G: don't show cut efficiencies
