#!/usr/bin/env bash

# Script to make data cards for Higgs Combine
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter
# You need to have a symbolic link called "trees" pointing to your trees

lumi=3000.

mca=susy-upgrade/mca_2LSOS.txt
trees=trees/
dirBins=susy-upgrade/bins/binning_5met_4mll_3slep/
dirCards=susy-upgrade/cards/

# If cards directory exists, exit
if [ -d "${dirCards}" ]; then
    echo "Cards directory ${dirCards} exists already."
    echo "Exit."
    exit
fi

mkdir -p "${dirCards}"

signals=()
signals+=(S_100_60_Delphes_v11)
signals+=(S_100_65_Delphes_v11)
signals+=(S_100_70_Delphes_v11)
signals+=(S_100_75_Delphes_v11)
signals+=(S_100_80_Delphes_v11)
signals+=(S_100_85_Delphes_v11)
signals+=(S_100_90_Delphes_v11)
signals+=(S_100_95_Delphes_v11)
signals+=(S_150_110_Delphes_v11)
signals+=(S_150_115_Delphes_v11)
signals+=(S_150_120_Delphes_v11)
signals+=(S_150_125_Delphes_v11)
signals+=(S_150_130_Delphes_v11)
signals+=(S_150_135_Delphes_v11)
signals+=(S_150_140_Delphes_v11)
signals+=(S_150_145_Delphes_v11)
signals+=(S_200_160_Delphes_v11)
signals+=(S_200_165_Delphes_v11)
signals+=(S_200_170_Delphes_v11)
signals+=(S_200_175_Delphes_v11)
signals+=(S_200_180_Delphes_v11)
signals+=(S_200_185_Delphes_v11)
signals+=(S_200_190_Delphes_v11)
signals+=(S_200_195_Delphes_v11)
signals+=(S_250_210_Delphes_v11)
signals+=(S_250_215_Delphes_v11)
signals+=(S_250_220_Delphes_v11)
signals+=(S_250_225_Delphes_v11)
signals+=(S_250_230_Delphes_v11)
signals+=(S_250_235_Delphes_v11)
signals+=(S_250_240_Delphes_v11)
signals+=(S_250_245_Delphes_v11)
signals+=(S_300_260_Delphes_v11)
signals+=(S_300_265_Delphes_v11)
signals+=(S_300_270_Delphes_v11)
signals+=(S_300_275_Delphes_v11)
signals+=(S_300_280_Delphes_v11)
signals+=(S_300_285_Delphes_v11)
signals+=(S_300_290_Delphes_v11)
signals+=(S_300_295_Delphes_v11)
signals+=(S_350_310_Delphes_v11)
signals+=(S_350_315_Delphes_v11)
signals+=(S_350_320_Delphes_v11)
signals+=(S_350_325_Delphes_v11)
signals+=(S_350_330_Delphes_v11)
signals+=(S_350_335_Delphes_v11)
signals+=(S_350_340_Delphes_v11)
signals+=(S_350_345_Delphes_v11)
signals+=(S_400_360_Delphes_v11)
signals+=(S_400_365_Delphes_v11)
signals+=(S_400_370_Delphes_v11)
signals+=(S_400_375_Delphes_v11)
signals+=(S_400_380_Delphes_v11)
signals+=(S_400_385_Delphes_v11)
signals+=(S_400_390_Delphes_v11)
signals+=(S_400_395_Delphes_v11)

for signal in "${signals[@]}"; do
    echo -n "Make datacards for signal point ${signal}... "
    for cuts in "${dirBins}"/*; do
        region="${cuts##*/}"
        region="${region%.*}"
        echo -n "${region}... "
        python makeCountingCards.py \
            <(sed "/${signal}/s/SkipMe *= *True/SkipMe=False/g" "${mca}") \
            "${cuts}" \
            -P "${trees}" \
            -l "${lumi}" \
            -j 20 \
            --s2v \
            --tree treeProducerSusyUpgrade \
            --obj Delphes \
            --AP \
            -p Wj2,DY2,tt,WW,"${signal}" \
            > "${dirCards}"/"${signal}"_"${cuts##*/}"
    done
    echo "Done."
done
