#!/usr/bin/env bash

# Script to make plots
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter
# You need to have a symbolic link called "trees" pointing to your trees

lumi=3000.

mca=susy-upgrade/mca_2LSOS.txt
cuts=susy-upgrade/cuts_2LSOS_2.txt
trees=trees/
plots=susy-upgrade/plots_2LSOS.txt

python mcPlots.py \
    "${mca}" \
    "${cuts}" \
    "${plots}" \
    -P "${trees}" \
    -l "${lumi}" \
    -j 22 \
    --s2v \
    --tree treeProducerSusyUpgrade \
    --obj Delphes \
    --maxRatioRange 0.05 1.95 \
    --fixRatioRange \
    --noErrorBandOnRatio \
    --noStackSig \
    --showIndivSigs \
    --showMCError \
    --emptyStack \
    --printBinAuto \
    --legendFontSize 0.028 \
    --noCms \
    --plotmode stack \
    --lspam "#bf{CMS} #it{Delphes Phase II Simulation Preliminary}, PU 200, 3 ab^{-1}, 14 TeV" \
    --rspam "" \
    --pdir plots_p2_fs_2e

# Useful options:
# -f: Only make plots for complete set of cuts
# -e: Show statistical errors
# --showIndivSigShapes: Don't normalize signal to cross section
# --emptyStack: Allow empty histograms
# --showRatio: Show ratio plot
# --ratioDen sample1: For --showRatio, use sample 1 in denominator
# --ratioNums sample2: For --showRatio, use sample 2 in numerator
# --ratioYLabel: Label for ratio plot
# --plotmode mode: Use plotting mode, e.g. nostack
# --printBinAuto: Show n GeV on y axis (works only for regular binning)
